import os
import glob

# Collect all raw CIF files for SARS-CoV-2 Wuhan strain proteins, 
# later may extend to new protein groups listed in config.yaml
#RAW_CIFS = glob.glob("data/proteins/empirical/sars_cov_2_wuhan/*/*.cif")
#TARGETS = [os.path.basename(os.path.dirname(cif)) for cif in RAW_CIFS]
#TARGETS = ['7UU9']
#METHODS = ['empirical', 'alphafold', 'colabfold']

# NOTE I think targets should be defined in a list of dicts
configfile: "config/config.yaml"

# Include the preparation pipeline rules
include: "rules/prep.smk"

# DYNAMIC ROUTING FUNCTION
# This function will dynamically determine the final targets for the Snakemake DAG based on the evaluation of the predicted models against the empirical structures. It checks if the predicted models are structurally divergent enough to warrant further processing (e.g., MD simulations) or if they should be rejected.
def get_final_targets(wildcards):
    targets = []
    
    for pdb in config["pdbs"]:
        # 1. Always schedule the empirical (native) structure for MD
        targets.append(f"results/gromacs/{pdb}/empirical/native/md/md_completed.txt")
        targets.append(f"results/{pdb}_empirical_native/movies/100ns_md_trajectory.mov")
        
        for source in config["prediction_sources"]:
            # 2. Force Snakemake to wait until the checkpoint finishes processing
            checkpoint_dir = checkpoints.evaluate_predictions.get(pdb=pdb, source=source).output.eval_dir
            
            # 3. Inspect JSON files to filter out "too_similar" models
            for json_file in os.listdir(checkpoint_dir):
                if json_file.endswith(".json"):
                    with open(os.path.join(checkpoint_dir, json_file)) as f:
                        eval_data = json.load(f)
                    
                    if eval_data["structural_evaluation"] == "divergent":
                        model_spec = eval_data["model"] # e.g., "model_1"
                        
                        # Add MD targets only for compliant models
                        targets.append(f"results/gromacs/{pdb}/{source}/{model_spec}/md/md_completed.txt")
                        targets.append(f"results/{pdb}_{source}_{model_spec}/movies/100ns_md_trajectory.mov")
                        
    return targets

rule all:
    input:
        get_final_targets
