# Protein list
#targets: ["7JPY", "7KPH", "8A55"]

#targets:
#  7UU9:
#    length_ns: 100
#  7KPH:
#    length_ns: 500

#default_compute_target: komondor # local, hpc
default_compute_target: local # local, hpc


#####################################
###### PDBs to prep and screen ######
#####################################

# Target structures to pull and model
pdbs:
  - 7UU9
#  - 7JPY
  - 7KQW
#  - 6WEY # for when only SA can be done // standrad cam ne supressed

# Prediction settings
prediction_sources:
  - alphafold
  - colabfold

# Total models generated per run (Standard ensemble size is 5)
model_numbers: [1, 2, 3, 4, 5]

# Alignment filtering parameters
rmsd_min_threshold: 1.5  # Ensure models are structurally unique/divergent enough

manual_prediction_dirs:
  alphafold: data/manual_predictions/alphafold/
  colabfold: data/manual_predictions/colabfold/

#####################################
###### MD logic overrides
###### - for < threshold screens
###### - for long runs
###### - for specialty requests like simulated annelation
#####################################



## Overrides for specific target runs
custom_simulations:
  7UU9:
    empirical_canonical_structure:
      - protocol: 'standard'
        compute_target: "HPC"
  7KQW:
    empirical_canonical_structure:
      - protocol: 'standard'
        compute_target: 'HPC'
    colabfold_model_1:
      - protocol: 'standard'
        compute_target: 'HPC'
    colabfold_model_2:
      - protocol: 'standard'
        compute_target: 'HPC'
    colabfold_model_3:
      - protocol: 'standard'
        compute_target: 'HPC'
    colabfold_model_4:
      - protocol: 'standard'
        compute_target: 'HPC'
    colabfold_model_5:
      - protocol: 'standard'
        compute_target: 'HPC'


#      - protocol: "simulated_annealing"
#      - compute_target: "local"
#    alphafold_model_1:
#      - protocol: 'standard' 
#      - compute_target: "HPC"
#      - protocol: "extended"
#       target_ns: 1000
#      - compute_target: "local"

